services:
  auth-worker:
    build:
      context: .
    container_name: hiveMind-auth-worker
    command: node services/auth/src/workers/email.worker.js
    env_file:
      - ./services/auth/.env.docker
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    container_name: hiveMind-redis
    restart: unless-stopped
    command:  redis-server --maxmemory 256mb --maxmemory-policy noeviction --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis-data: